
CREATE TABLE `DOCTOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) COLLATE ascii_bin DEFAULT NULL,
  `DATE-OF-BIRTH` timestamp NULL DEFAULT NULL,
  `QUALIFICATION` varchar(45) COLLATE ascii_bin DEFAULT NULL,
  `BACHELORS-COMLETION-DATE` timestamp NULL DEFAULT NULL,
  `ADDRESS` varchar(200) COLLATE ascii_bin DEFAULT NULL,
  `PHONE` varchar(15) COLLATE ascii_bin DEFAULT NULL,
  `EMAIL` varchar(45) COLLATE ascii_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=ascii COLLATE=ascii_bin;

CREATE TABLE `PATIENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) COLLATE ascii_bin NOT NULL,
  `DATE_OF_BIRTH` timestamp NULL DEFAULT NULL,
  `FATHER_NAME` varchar(45) COLLATE ascii_bin DEFAULT NULL,
  `MOTHER_NAME` varchar(45) COLLATE ascii_bin DEFAULT NULL,
  `ADDRESS` varchar(200) COLLATE ascii_bin DEFAULT NULL,
  `MOBILE` varchar(15) COLLATE ascii_bin DEFAULT NULL,
  `EMAIL` varchar(45) COLLATE ascii_bin DEFAULT NULL,
  `GENDER` varchar(1) COLLATE ascii_bin NOT NULL,
  `age` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=ascii COLLATE=ascii_bin;
CREATE TABLE `APPOINTMENTS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_VISIT` timestamp NULL DEFAULT NULL,
  `FOLLOWUP` timestamp NULL DEFAULT NULL,
  `DOCTORID` bigint(20) NOT NULL,
  `PATIENTID` bigint(20) NOT NULL,
  `DESCRIPTION` varchar(500) COLLATE ascii_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DOCTORS_idx` (`DOCTORID`),
  KEY `PATIENTS_idx` (`PATIENTID`),
  CONSTRAINT `DOCTORS` FOREIGN KEY (`DOCTORID`) REFERENCES `DOCTOR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PATIENTS` FOREIGN KEY (`PATIENTID`) REFERENCES `PATIENT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=ascii COLLATE=ascii_bin;

CREATE TABLE `DOCTOR_PATIENT` (
  `DOCTOR_ID` bigint(20) NOT NULL,
  `PATIENT_ID` bigint(20) NOT NULL,
  `FEEDBACK_EMAIL_SENT` tinyint(4) DEFAULT '0',
  KEY `DOCTOR_idx` (`DOCTOR_ID`),
  KEY `PATIENT_idx` (`PATIENT_ID`),
  CONSTRAINT `DOCTOR` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `DOCTOR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PATIENT` FOREIGN KEY (`PATIENT_ID`) REFERENCES `PATIENT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;

